/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.autonoma.gnomito.gui;

import co.edu.autonoma.gnomito.Contenedor;
import co.edu.autonoma.gnomito.sprites.Jardin;
import java.awt.Graphics;
import java.awt.event.KeyEvent;

/**
 *
 * @author educacion
 */
public class VentanaJuego 
        extends javax.swing.JFrame
        implements Contenedor
{

    private Jardin jardin;
    
    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego() {
        initComponents();
    }

    public void setJardin(Jardin jardin) {
        this.jardin = jardin;
    }
    
    @Override
    public void paint(Graphics g)
    {
        if(jardin != null)
            jardin.dibujar(g);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_B)
            jardin.keyPressed(KeyEvent.VK_B);

        if(evt.getKeyCode() == KeyEvent.VK_M)
            jardin.keyPressed(KeyEvent.VK_M);
        
        if(evt.getKeyCode() == KeyEvent.VK_UP |
           evt.getKeyCode() == KeyEvent.VK_DOWN |
           evt.getKeyCode() == KeyEvent.VK_LEFT |
           evt.getKeyCode() == KeyEvent.VK_RIGHT)
            jardin.keyPressed(evt.getKeyCode());
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        Jardin jardin = new Jardin(0, 0, 800, 600);
        
        VentanaJuego ventana = new VentanaJuego();
        ventana.setTitle("El juego del Gnomito");
        ventana.setJardin(jardin);
        jardin.setContenedor(ventana);
        ventana.setSize(800, 600);
//        ventana.setResizable(false);
        ventana.setVisible(true);
    }

    @Override
    public void refrescar() {
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
